name: Clean up releases
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      keep:
        description: "Number of releases to keep (default: 100)"
        required: true
        default: "100"
        type: string

jobs:
  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: ${{ inputs.keep }}
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
